### ISSUE TITLE
Displaying the YT video only where URL is filled

### ISSUE THREAD

**Issue by mariantanase** [brianteeman/ytlite#1]
Hi Brian,
Thanks for this plugin.
I want to ask you how to deal with articles where are no URLs ?
I don't want anything to appear if url is not filled in.
It's possible ?

![yvideo](https://user-images.githubusercontent.com/3976174/203333412-420b7667-286b-4bd7-bd4c-20def463411b.png)

**Comment by brianteeman** [comment]
ouch - looks like a bug on my end. will check tonight - thanks for reporting it

**Comment by brianteeman** [comment]
Fixed the bug and made a new release whicvh should show up on your site as an available update.

If for any reason it wont update or it doesnt report an update is available just download the new release and install it over the top

https://github.com/brianteeman/ytlite/releases/tag/1.0.1

**Comment by mariantanase** [comment]
I confirm that with the automatic update the bug is fixed.
Thanks!

![fix](https://user-images.githubusercontent.com/3976174/203352651-95c53ed2-fab8-4dad-b3ad-36309a09ffd8.png)
